# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: Tests and coverage 

on: [push, pull_request]

env:
  cntr: gvegayon/epiworld:latest

jobs:
  test-ubuntu:
    container: gvegayon/epiworld:latest
    runs-on: Ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check
        env:
          OPENMP: -fopenmp
        run: |
          make all-examples
  test-macos:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check
        run: |
          brew install llvm@14 
          echo 'export PATH="/usr/local/opt/llvm@14/bin:$PATH"' >> /Users/runner/.bash_profile
          cd tests && make main.a && ./main.a

  test-ubuntu2:
    runs-on: ubuntu-latest
    container: gvegayon/epiworld:latest

    steps:
      - uses: actions/checkout@v4

      - name: Check
        env:
          OPENMP: -fopenmp
        run: |
          cd tests
          make main.o
          ./main.o
        
  coverage:
    runs-on: ubuntu-latest
    container: gvegayon/epiworld:latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Generate coverage
        run: |
          cd tests
          make coverage

      - uses: codecov/codecov-action@v4.4.1
        with:
          files: tests/gcov-files/* # optional
          #        flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)