# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: Code coverage

on: [push, pull_request]

jobs:        
  coverage:
    runs-on: ubuntu-latest
    container: gvegayon/epiworld:latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Generate coverage
        run: |
          cd tests
          make coverage

      - uses: codecov/codecov-action@v3
        with:
          # gcov: true
          directory: tests
          gcov_ignore: tests/tests.hpp
          verbose: true # optional (default = false)
          token: ${{ secrets.CODECOV_TOKEN }}
